version = 2

editor = []
get_on_with_it_message = "yes"

[snippets]

[model]
round_robin = []

[skills]
include = []
exclude = []

[sandbox]
read = []
write = []
exec = []
home = []

[bar.top]
left = [
    { segment = "activity-spinner", idle = "✧·", frames = ["✦·", "·✦", "·✧", "✧·"], rate = "125ms" },
    { segment = "turn-elapsed" },
    { segment = "last-tps" },
]
center = [
    { segment = "context-usage" },
]
right = [
    { segment = "working-directory", type = "short" },
    { segment = "scroll-overflow", direction = "up" }
]

[bar.bottom]
left = [
    { segment = "mode-toggle" },
]
center = [
    { segment = "active-model" },
]
right = [
    { segment = "current-session" },
    { segment = "scroll-overflow", direction = "down" }
]
