version = 9

[editor]
command = []

[input]
continue = "yes"

[ui]
stream = "line"

[snippets]

[model]
round_robin = []

[provider.ollama]
host = ""

[skills]
include = []
exclude = []

[sandbox]
read = []
write = []
exec = []
home = []

[bar.top]
left = [
    { segment = "activity-spinner", idle = "·✦·", frames = ["✦··", "·✦·", "··✦", "··✦", "·✦·", "✦··"], rate = "125ms" },
]
center = []
right = [
    { segment = "session-name", emoji = true },
    { segment = "scroll-overflow", direction = "up" }
]

[bar.bottom]
left = [
    { segment = "mode-toggle" },
    { segment = "workspace-dir", type = "base" },
]
center = [
    { segment = "active-model" },
    { segment = "context-usage" },
]
right = [
    { segment = "subscription-usage" },
    { segment = "scroll-overflow", direction = "down" }
]
